name: CI

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  coverage:
    runs-on: ubuntu-latest
    env:
      OS: ubuntu-latest
      PYTHON: '3.9'
    steps:
    - uses: actions/checkout@v3

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.9

    - name: Generate coverage report
      run: |
        python -m pip install poetry
        poetry install --with test
        poetry run pytest --cov=src/powerline_k8s --cov-report=xml

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v2
      with:
        files: ./coverage.xml
        env_vars: OS,PYTHON
        fail_ci_if_error: true
        verbose: true
