name: Publish docs to GitHub Pages

on:
  push:
    tags:
      - 'v*.*.*'
  workflow_dispatch:

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python 3.7
        uses: actions/setup-python@v4
        with:
          python-version: 3.7

      - name: Generate docs
        run: |
          python -m pip install poetry
          poetry install
          poetry run pdoc -o docs src/powerline_k8s

      - uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs
